#!/usr/bin/env bash
# It displays the content of the current working directory in list format.
#+displaying the part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
